[tool.poetry]
name = "asynctkinter"
version = "0.1.1"
description = "async library that works on top of tkinter's event loop"
authors = ["Nattōsai Mitō <flow4re2c@gmail.com>"]
license = "MIT"
readme = 'README.md'
repository = 'https://github.com/gottadiveintopython/asynctkinter'
homepage = 'https://github.com/gottadiveintopython/asynctkinter'
keywords = ['async', 'tkinter', ]
classifiers=[
    'Development Status :: 5 - Production/Stable',
    'License :: OSI Approved :: MIT License',
    'Intended Audience :: Developers',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3.7',
    'Topic :: Software Development :: Libraries',
    'Operating System :: OS Independent',
]

[tool.poetry.dependencies]
python = "^3.7"
asyncgui = "^0.1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
